# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170824_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
