# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('profiles', '0003_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user_group', to='auth.Group'),
        ),
    ]
